# Clearing the environment ----
rm(list=ls())

# Import lpSolve package ----
library(lpSolve)

# part a) --------------------------------------------------

# Set Coefficients of Obj Function
f.obj <- c(3600, 5400)

# Set a Matrix corresponding to constraints coeff
f.con <- matrix(c(6, 10.5,
                  4, 2,
                  0, 1), nrow = 3, byrow = TRUE)

# Set inequality signs
f.dir <- c("<=",
           "<=",
           "<=")

# Set right-hand side parameters
f.par <- c(48000,
           20000,
           3500)

# Final value (Profit)
lp("max", f.obj, f.con, f.dir, f.par)

# Final values
lp("max", f.obj, f.con, f.dir, f.par)$solution


# part b) --------------------------------------------------

# The Cruiser demand constraint is not binding.
# No changes needed.


# part c) --------------------------------------------------

# The new rhs of the labor constraint becomes 48,000 * 1.25 = 60,000.

# Set right-hand side parameters
f.par[1] <- 60000

# Final value (Profit)
lp("max", f.obj, f.con, f.dir, f.par)

# Final values
lp("max", f.obj, f.con, f.dir, f.par)$solution


# part d) --------------------------------------------------

# Overtime increases profit by $30,600,000 – $26,640,000 = $3,960,000.
# Rachel should pay at most $3,960,000 extra for overtime labor.


# part e) --------------------------------------------------

# RHS of the Cruiser demand constraint is 3,500 * 1.20 = 4,200 cars.
# RHS of the labor hour constraint is 48,000 * 1.25 = 60,000 hours.

# Set right-hand side parameters
f.par[3] <- 4200

# Final value (Profit)
lp("max", f.obj, f.con, f.dir, f.par)

# Final values
lp("max", f.obj, f.con, f.dir, f.par)$solution


# part f) --------------------------------------------------

# The advertising campaign costs $500,000.
# Use of overtime labor costs $1,600,000.
# Thus, the extra cost is $500,000 + $1,600,000 = $2,100,000.
# Profit in part (e): $32,400,000
# Net Profit (profit - cost of campaign and overtime) is: $30,300,000
# Profit in part (a): $26,640,000
# We compare the $30,300,000 profit with the $26,640,000 profit in part (a).
# Run the advertising campaign and use overtime labor is a profitable decision.


# part g) --------------------------------------------------

# We now change the profit for the Thrillseeker from $3,600 to $2,800.

# Set Coefficients of Obj Function
f.obj[1] <- 2800

# Set right hand side parameters to original values
f.par <- c(48000,
           20000,
           3500)

# Final value (Profit)
lp("max", f.obj, f.con, f.dir, f.par)

# Final values
lp("max", f.obj, f.con, f.dir, f.par)$solution


# part h) --------------------------------------------------

# Each Thrillseeker now requires 7.5 hours for assembly.

# Set Coefficients of Obj Function
f.obj[1] <- 3600

# Set a Matrix corresponding to constraints coeff
f.con[1, 1] <- 7.5

# Final value (Profit)
lp("max", f.obj, f.con, f.dir, f.par)

# Final values
lp("max", f.obj, f.con, f.dir, f.par)$solution

# part i) --------------------------------------------------

# The number of Cruisers has to be strictly equal to the total demand.

# Set inequality signs
f.dir[3] <- "="

# All constraints go back to the original solution
f.con <- matrix(c(6, 10.5,
                  4, 2,
                  0, 1), nrow = 3, byrow = TRUE)

# Final value (Profit)
lp("max", f.obj, f.con, f.dir, f.par)

# Final values
lp("max", f.obj, f.con, f.dir, f.par)$solution


# part j) --------------------------------------------------

# Combine considerations in parts (f), (g), and (h).
# In part (f), we decided to use the ad campaign and overtime labor.
# The advertising campaign raises the demand for the Cruiser to 4,200 sedans.
# The overtime labor increases the labor hour capacity of the plant to 60,000.
# In part (g), we decreased the profit generated by a Thrillseeker to $2,800.
# In part (h), we increased the time to assemble a Thrillseeker to 7.5 hours.

# Set Coefficients of Obj Function
f.obj[1] <- 2800

# Set a Matrix corresponding to constraints coeff
f.con[1, 1] <- 7.5

# Set right-hand side parameters
f.par[1] <- 60000
f.par[3] <- 4200

# Final value (Profit)
lp("max", f.obj, f.con, f.dir, f.par)

# Final values
lp("max", f.obj, f.con, f.dir, f.par)$solution
